//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprawdzenieOsobyServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ksip.policja.gov.pl/SprawdzenieOsobyWRDService", ConfigurationName="SprawdzenieOsobyServiceReference.PersonService")]
    public interface PersonService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="um:opSprawdzenieOsoby", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SprawdzenieOsobyServiceReference.SprawdzenieOsobyWRDResponse> SprawdzenieOsobyWRDAsync(SprawdzenieOsobyServiceReference.SprawdzenieOsobyWRDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyRequest : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private SprawdzenieOsobyRequestRequestHeader requestHeaderField;
        
        private SprawdzenieOsobyRequestRequestBody requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SprawdzenieOsobyRequestRequestHeader RequestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SprawdzenieOsobyRequestRequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
                this.RaisePropertyChanged("RequestBody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyRequestRequestHeader : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string requestIDField;
        
        private System.DateTime timestampField;
        
        private SprawdzenieOsobyRequestRequestHeaderAuditRecord auditRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
                this.RaisePropertyChanged("RequestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
                this.RaisePropertyChanged("Timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SprawdzenieOsobyRequestRequestHeaderAuditRecord AuditRecord
        {
            get
            {
                return this.auditRecordField;
            }
            set
            {
                this.auditRecordField = value;
                this.RaisePropertyChanged("AuditRecord");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyRequestRequestHeaderAuditRecord : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private SystemType systemNameField;
        
        private string applicationNameField;
        
        private string moduleNameField;
        
        private string terminalNameField;
        
        private SprawdzenieOsobyRequestRequestHeaderAuditRecordUserProfile userProfileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SystemType SystemName
        {
            get
            {
                return this.systemNameField;
            }
            set
            {
                this.systemNameField = value;
                this.RaisePropertyChanged("SystemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string ApplicationName
        {
            get
            {
                return this.applicationNameField;
            }
            set
            {
                this.applicationNameField = value;
                this.RaisePropertyChanged("ApplicationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string ModuleName
        {
            get
            {
                return this.moduleNameField;
            }
            set
            {
                this.moduleNameField = value;
                this.RaisePropertyChanged("ModuleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
        public string TerminalName
        {
            get
            {
                return this.terminalNameField;
            }
            set
            {
                this.terminalNameField = value;
                this.RaisePropertyChanged("TerminalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SprawdzenieOsobyRequestRequestHeaderAuditRecordUserProfile UserProfile
        {
            get
            {
                return this.userProfileField;
            }
            set
            {
                this.userProfileField = value;
                this.RaisePropertyChanged("UserProfile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public enum SystemType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("US Opole")]
        USOpole,
        
        /// <remarks/>
        GITD,
        
        /// <remarks/>
        CANARD,
        
        /// <remarks/>
        ŻW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyRequestRequestHeaderAuditRecordUserProfile : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string userIDField;
        
        private string unitIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string UnitID
        {
            get
            {
                return this.unitIDField;
            }
            set
            {
                this.unitIDField = value;
                this.RaisePropertyChanged("UnitID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class PersonOffencesRecordResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.DateTime incidentDateField;
        
        private bool incidentDateFieldSpecified;
        
        private System.DateTime finePaymentDateField;
        
        private bool finePaymentDateFieldSpecified;
        
        private System.DateTime validationOfDecisonDateField;
        
        private bool validationOfDecisonDateFieldSpecified;
        
        private PersonCriminalRecordClassificationType[] personCriminalRecordClassificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime IncidentDate
        {
            get
            {
                return this.incidentDateField;
            }
            set
            {
                this.incidentDateField = value;
                this.RaisePropertyChanged("IncidentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncidentDateSpecified
        {
            get
            {
                return this.incidentDateFieldSpecified;
            }
            set
            {
                this.incidentDateFieldSpecified = value;
                this.RaisePropertyChanged("IncidentDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime FinePaymentDate
        {
            get
            {
                return this.finePaymentDateField;
            }
            set
            {
                this.finePaymentDateField = value;
                this.RaisePropertyChanged("FinePaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinePaymentDateSpecified
        {
            get
            {
                return this.finePaymentDateFieldSpecified;
            }
            set
            {
                this.finePaymentDateFieldSpecified = value;
                this.RaisePropertyChanged("FinePaymentDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ValidationOfDecisonDate
        {
            get
            {
                return this.validationOfDecisonDateField;
            }
            set
            {
                this.validationOfDecisonDateField = value;
                this.RaisePropertyChanged("ValidationOfDecisonDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidationOfDecisonDateSpecified
        {
            get
            {
                return this.validationOfDecisonDateFieldSpecified;
            }
            set
            {
                this.validationOfDecisonDateFieldSpecified = value;
                this.RaisePropertyChanged("ValidationOfDecisonDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonCriminalRecordClassification", Order=3)]
        public PersonCriminalRecordClassificationType[] PersonCriminalRecordClassification
        {
            get
            {
                return this.personCriminalRecordClassificationField;
            }
            set
            {
                this.personCriminalRecordClassificationField = value;
                this.RaisePropertyChanged("PersonCriminalRecordClassification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class PersonCriminalRecordClassificationType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string legalClassificationCodeField;
        
        private string classificationCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string LegalClassificationCode
        {
            get
            {
                return this.legalClassificationCodeField;
            }
            set
            {
                this.legalClassificationCodeField = value;
                this.RaisePropertyChanged("LegalClassificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string ClassificationCode
        {
            get
            {
                return this.classificationCodeField;
            }
            set
            {
                this.classificationCodeField = value;
                this.RaisePropertyChanged("ClassificationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyRequestRequestBody : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NrPESEL", typeof(object), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Person", typeof(SprawdzenieOsobyRequestRequestBodyPerson), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyRequestRequestBodyPerson : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private SprawdzenieOsobyRequestRequestBodyPersonPersonName personNameField;
        
        private System.DateTime birthDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SprawdzenieOsobyRequestRequestBodyPersonPersonName PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
                this.RaisePropertyChanged("PersonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyRequestRequestBodyPersonPersonName : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private SprawdzenieOsobyResponsePerson personField;
        
        private PersonOffencesRecordResponseType[] offenseRecordField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SprawdzenieOsobyResponsePerson Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
                this.RaisePropertyChanged("Person");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OffenseRecord", Order=1)]
        public PersonOffencesRecordResponseType[] OffenseRecord
        {
            get
            {
                return this.offenseRecordField;
            }
            set
            {
                this.offenseRecordField = value;
                this.RaisePropertyChanged("OffenseRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyResponsePerson : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private SprawdzenieOsobyResponsePersonPersonName personNameField;
        
        private string pESELNumberField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SprawdzenieOsobyResponsePersonPersonName PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
                this.RaisePropertyChanged("PersonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PESELNumber
        {
            get
            {
                return this.pESELNumberField;
            }
            set
            {
                this.pESELNumberField = value;
                this.RaisePropertyChanged("PESELNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
                this.RaisePropertyChanged("BirthDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby")]
    public partial class SprawdzenieOsobyResponsePersonPersonName : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzenieOsobyWRDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby", Order=0)]
        public SprawdzenieOsobyServiceReference.SprawdzenieOsobyRequest SprawdzenieOsobyRequest;
        
        public SprawdzenieOsobyWRDRequest()
        {
        }
        
        public SprawdzenieOsobyWRDRequest(SprawdzenieOsobyServiceReference.SprawdzenieOsobyRequest SprawdzenieOsobyRequest)
        {
            this.SprawdzenieOsobyRequest = SprawdzenieOsobyRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzenieOsobyWRDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://policja.gov.pl/RuchDrogowy/SprawdzenieOsoby", Order=0)]
        public SprawdzenieOsobyServiceReference.SprawdzenieOsobyResponse SprawdzenieOsobyResponse;
        
        public SprawdzenieOsobyWRDResponse()
        {
        }
        
        public SprawdzenieOsobyWRDResponse(SprawdzenieOsobyServiceReference.SprawdzenieOsobyResponse SprawdzenieOsobyResponse)
        {
            this.SprawdzenieOsobyResponse = SprawdzenieOsobyResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PersonServiceChannel : SprawdzenieOsobyServiceReference.PersonService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<SprawdzenieOsobyServiceReference.PersonService>, SprawdzenieOsobyServiceReference.PersonService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PersonServiceClient() : 
                base(PersonServiceClient.GetDefaultBinding(), PersonServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PersonPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PersonServiceClient.GetBindingForEndpoint(endpointConfiguration), PersonServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PersonServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PersonServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SprawdzenieOsobyServiceReference.SprawdzenieOsobyWRDResponse> SprawdzenieOsobyServiceReference.PersonService.SprawdzenieOsobyWRDAsync(SprawdzenieOsobyServiceReference.SprawdzenieOsobyWRDRequest request)
        {
            return base.Channel.SprawdzenieOsobyWRDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SprawdzenieOsobyServiceReference.SprawdzenieOsobyWRDResponse> SprawdzenieOsobyWRDAsync(SprawdzenieOsobyServiceReference.SprawdzenieOsobyRequest SprawdzenieOsobyRequest)
        {
            SprawdzenieOsobyServiceReference.SprawdzenieOsobyWRDRequest inValue = new SprawdzenieOsobyServiceReference.SprawdzenieOsobyWRDRequest();
            inValue.SprawdzenieOsobyRequest = SprawdzenieOsobyRequest;
            return ((SprawdzenieOsobyServiceReference.PersonService)(this)).SprawdzenieOsobyWRDAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PersonPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PersonPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8011/SprawdzenieOsobyWRDService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PersonServiceClient.GetBindingForEndpoint(EndpointConfiguration.PersonPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PersonServiceClient.GetEndpointAddress(EndpointConfiguration.PersonPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PersonPort,
        }
    }
}
